DROP INDEX IF EXISTS payouts_notifications_executed_time_idx;
DROP TABLE IF EXISTS payouts_notifications;
DROP SEQUENCE IF EXISTS payouts_notifications_id_seq;
DROP TABLE IF EXISTS wallet_workers;
DROP SEQUENCE IF EXISTS user_wallets_id_seq;
DROP TABLE IF EXISTS user_wallets;
DROP TABLE IF EXISTS user_actions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS blockchains;
